[tool.poetry]
name = "mapviewer"
version = "3.1.6"
description = ""
authors = ["David Brooks <d.brooks@auckland.ac.nz>"]

[tool.poetry.dependencies]
python = "^3.8"
markupsafe = "2.0.1"
sphinx = "4.5.0"
sphinx-js = "*"
sphinx-rtd-theme = "*"
